# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: 
    - /*

permissions:
  contents: read

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
    - name: Linting
      run: |
        python -m pylint --max-module-lines 2000 --max-line-length 150 main/*.py
        python -m pylint --disable all --enable spelling --spelling-dict en_US --spelling-ignore-words "sys" main/*.py
    - name: Runtime Errors
      run: |
        python main/main.py
    - name: Test with pytest
      run: |
        python -m pytest main/test/main_test.py 
